#%RAML 1.0 NamedExample

value:
- id: 1
  name: "Pepé"
  dni: 0000001
  address: "Av Santa Fe 111"
  tel: 12345789
  state: true
- id: 2
  name: "Fulanito"
  dni: 0000002
  address: "Av Cordoba 123"
  tel: 987654321
  state: true
- id: 3
  name: "Menganito"
  dni: 0000003
  address: "Av Corrientes 5555"
  tel: 2525252525
  state: true
